# Generated by Django 5.2.1 on 2025-05-11 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=20)),
                ('father_occuption', models.CharField(max_length=20)),
                ('father_mobile', models.IntegerField(max_length=10)),
                ('father_email', models.EmailField(max_length=254)),
                ('mother_name', models.CharField(max_length=20)),
                ('mother_occuption', models.CharField(max_length=20)),
                ('mother_mobile', models.IntegerField(max_length=10)),
                ('mother_email', models.EmailField(max_length=254)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('student_id', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10)),
                ('student_class', models.CharField(max_length=20)),
                ('religion', models.CharField(choices=[('hindu', 'hindu'), ('christian', 'christian'), ('others', 'others')], max_length=20)),
                ('joining_date', models.DateField()),
                ('mobile_number', models.IntegerField(max_length=10)),
                ('addmission_number', models.IntegerField(max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=20)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20)),
                ('student_image', models.ImageField(upload_to='student_image')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('parents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.parents')),
            ],
        ),
    ]
