# Generated by Django 5.2.1 on 2025-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='father_mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='parents',
            name='mother_mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='addmission_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.BigIntegerField(),
        ),
    ]
